Inflate MsgMultiSend and other missing types
gagbo/lib-ledger-core pull request #29
Opened 2020-03-23 13:20 UTC by gagbo

MsgMultiSend uses another database to store the arbitrarily sized array
of inputs and outputs for the transaction.

All the missing types in inflateMessage have been added.

2020-03-24 12:12 UTC, ghost requested changes

2020-03-24 12:12 UTC, ghost commented on core/src/wallet/cosmos/database/CosmosLikeTransactionDatabaseHelper.cpp
> +                                soci::stringToCoins(multiSendRow.get<std::string>(COL_MULTI_TO), newInput.coins);
`COL_MULTI_AMT` instead of `COL_MULTI_TO`?

2020-03-24 12:12 UTC, ghost commented on core/src/wallet/cosmos/database/CosmosLikeTransactionDatabaseHelper.cpp
> +                                soci::stringToCoins(multiSendRow.get<std::string>(COL_MULTI_TO), newOutput.coins);
`COL_MULTI_AMT` instead of `COL_MULTI_TO`?

2020-03-24 12:12 UTC, haammar-ledger commented on core/src/wallet/cosmos/database/CosmosLikeTransactionDatabaseHelper.cpp
> +                               "VALUES (:uid, :tuid, :mt, :log, :success, :mi, :fa, :ta, :amount)",
Remove `:fa` and `:ta` ?

2020-03-25 11:45 UTC, gagbo commented on core/src/wallet/cosmos/database/CosmosLikeTransactionDatabaseHelper.cpp
> +                                soci::stringToCoins(multiSendRow.get<std::string>(COL_MULTI_TO), newInput.coins);
Classic story of the guy who wanted to use names for magic numbers and then gets caught shamelessly copy-pasting :)

2020-03-25 12:00 UTC, gagbo commented
I'll use this small PR to fix as much of the CI as possible (i.e. reach tests at least)

2020-03-25 12:19 UTC, haammar-ledger commented on core/src/wallet/cosmos/database/CosmosLikeTransactionDatabaseHelper.cpp
> +                                soci::stringToCoins(multiSendRow.get<std::string>(COL_MULTI_TO), newInput.coins);
Way easier to spot copy/pasta with names than numbers though, so kind of a win :)

2020-03-25 12:29 UTC, ghost approved these changes

2020-03-26 08:23 UTC, merged